name: GitHub Snake Game

on:
  # jalan tiap jam 00:00 UTC
  schedule:
    - cron: "0 0 * * *"
  # bisa dijalankan manual dari tab Actions
  workflow_dispatch:
  # jalan kalau ada push ke branch main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate snake animation
      - name: Generate GitHub Contributions Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-ocean.svg?color_snake=#ff7518&color_dots=#90e0ef,#00b4d8,#0077b6,#03045e

      # Step 3: Deploy ke branch output
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "chore: update snake animation [skip ci]"
